name: publish_automatizado_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    bundle: flutter build appbundle
    apk_run: flutter build apk --split-per-abi
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
    adb: adb connect localhost:21503
    appbundle: flutter build appbundle
    apk: flutter build apk --split-per-abi
    appbundle_apk: $bundle & $apk_run

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.1
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  flutter_spinkit: ^5.0.0
  asuka: ^2.0.0-nullsafety.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  flutter_modular_test: ^1.0.1
  flutter_launcher_icons: ^0.9.0  
  mobx_codegen: ^2.0.1+3
  msix: ^2.2.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  
  image_path: "assets/PA.png"

flutter:
  uses-material-design: true
  assets:
    - assets/PA.png